# Generated by Django 4.2.5 on 2023-09-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="l", upload_to="product_images/"),
            preserve_default=False,
        ),
    ]
